### PR TITLE
📝 Validation

### PR DESCRIPTION
**Pull request by brunobuddy**
## Description

This PR adds the core feature of **validation** to Manifest.

It also refactors the monorepo adding [turbo](https://turbo.build) to save time and prevent errors on packing and versioning:

- Unique commands for install, `build`, `dev` and `test` for the whole repo. 
- Deprecate `@mnfst/admin` and `@mnfst/types` packages (no longer needed)
-  Integrates the JS SDK in the monorepo
- CI/CD that builds and tests all the packages working together

### Workspaces

- Ensure that the `CONTRIBUTING.md` and follow the *getting started* guide at the end of the file
- Make sure that root scripts do not throw errors: `npm run build`, `npm run test` and `npm run dev`

### Validation

- First update your **website** repo to the [last PR](https://github.com/mnfst/website/pull/27)
- Then launch the docs and you should be able to see the `Validation` link in the sidebar under `Entities and Properties`
- From the repo run `npm install` then `npm install --workspaces` and the `npm run dev` to launch the admin panel and the backend
- The best way to test validation is using Postman or similar tools, following the REST API Documentation 

#### Important thinks to check
- Make sure that the doc is clear
- Ensure that the DX is nice on the YAML file. The JSON Schema should show popups that link to the validation doc, intellisense and correct syntax highlighting
- Have a look about all tests specs (starting with `it(`) to see if you agree: `packages/core/manifest/e2e/tests/validation.e2e-spec.ts`, `packages/core/manifest/src/validation/tests/type-validators.spec.ts`

## Issues created

I created 2 issues that in my opinion are not mandatory and can be done later (post MVP):
- #143 
- #144 

## Impacted packages

Check the packages that require a new publication or release:

- [x] @mnfst/manifest
- [x] @mnfst/js-sdk
- [x] doc

## Check list before submitting

- [x] I have performed a self-review of my code (no debugs, no commented code, good naming, etc.)
- [x] I wrote the relative tests
- [x] I updated the documentation if necessary
- [x] This PR is wrote in a clear language and correctly labeled

### CODE REVIEW

**Comment by SebConejo** [comment]
@brunobuddy 
1. Is there a way to automatically answer "no" to the questions Angular asks during ng serve?
Capture d’écran 2024-09-18 à 16 46 35

2. An error appears on the console.
Capture d’écran 2024-09-18 à 16 34 47


3. We should add to the documentation, the ".env" instructions. The user needs to copy and past the .env.example. Then he have to add an environment value that will affect somehting. Or if it's unnecessary. Seeing that file without instruction is fuzzy.

**Comment by SebConejo** [comment]
@brunobuddy On the admin panel, If a field is required, the input should receive the required attribute. And, if you add an attribute to the <app-input> tag, I could manage it to display a small red star next to the label name *
Capture d’écran 2024-09-18 à 18 39 31

Capture d’écran 2024-09-18 à 18 39 25

**Comment by SebConejo** [comment]
@brunobuddy I removed **only from the doc** the following validators :

- minDate
- maxDate
- arrayContains
- arrayNotContains
- arrayNotEmpty
- arrayMinSize
- arrayMaxSize

Moreover, I'm wondering if this validator is necessary : `isMimeType`.

As we don't have file or image field yet. But I think it's not necessary to remove it because it doesn't create errors. It is just unnecessary until we will include the **image** feature. 

--

Then, I tested each validator, one by one,by using the admin panel create form. All the others work well.

**Comment by brunobuddy** [comment]
@SebConejo OK I will remove arrays and dates validators for now. I can remove isMimeType to until we get the image feature

**Review by SebConejo — APPROVED** [review]

**Pull request merged**
