### PR TITLE
Uploads

### PR DESCRIPTION
**Pull request by brunobuddy**
## Description

This PR adds **file and image upload** to Manifest

## How can it be tested?

- First pull the develop branch of the website repository and launch the docs following the README.md. You should see the new Uploads doc now
- From this repo, run npm run dev and play around with your `/packages/core/manifest/manifest/backend.yml`
- Play around with new upload and file/image properties based on the doc
- You can see the results through the admin panel and REST API  (through Postman).

:warning: I am thinking about a good way to test JS SDK features easily. It is not possible right now.

## Impacted packages

Check the packages that require a new publication or release:

- [x] [manifest](https://www.npmjs.com/package/manifest)
- [x] [@mnfst/sdk](https://www.npmjs.com/package/@mnfst/sdk)

## Check list before submitting

- [x] I have performed a self-review of my code (no debugs, no commented code, good naming, etc.)
- [x] I wrote the relative tests
- [x] I updated the documentation if necessary
- [x] This PR is wrote in a clear language and correctly labeled

### CODE REVIEW

**Comment by SebConejo** [comment]
@brunobuddy I don't understand how to post an image using the rest API. Maybe you forgot something on the doc no ? I mean, you are showing a post without any image. So this example can't work. 

If I want to post an image to the cat 48. I write that POST request: 
`
POST http://localhost:1111/storage/cats/photo/Oct2024/1s8ug10j7m1qpixp5-thumbnail.jpg?property=image&entity=cats&id=48
`
I receive a 404 error :
`
http://localhost:1111/storage/cats/photo/Oct2024/1s8ug10j7m1qpixp5-thumbnail.jpg?property=image&entity=cats&id=48
`

**Comment by brunobuddy** [comment]
@SebConejo 

To post a multipart form-data request with an image using Postman, follow these steps:

Open Postman: Make sure you have Postman installed and running.

Create a new request:

Click on the + button to open a new tab.
Select the POST method.
Set the URL: Enter the URL where you want to send the request (e.g., your API endpoint).

Go to the "Body" tab:

Select the Body tab below the URL bar.
Choose form-data from the body options.
Add form-data fields:

In the first row under the Key column, enter the name of the field for the image file. For example, you can use "file", "image", or whatever your API expects.
In the Value column, click the dropdown on the right and choose File.
After selecting File, click on Select Files to upload the image from your system.
Add other fields if needed:

If your form-data includes additional fields (e.g., text fields), add more rows in the Key and Value columns and specify the type of each field (Text or File) as required.
Send the request:

Click on the Send button to post the request to the server.
You should receive a response from the server depending on your API configuration.
And that's it! You've just posted a multipart form-data request with an image using Postman. 🐺 Woof!

**Comment by SebConejo** [comment]
doing that generate a repsonse with this images.But then, I can see the images. 
Capture d’écran 2024-10-01 à 20 14 57
Capture d’écran 2024-10-01 à 20 15 14

Mon code sur l'image des cats: 
Capture d’écran 2024-10-01 à 20 20 02

**Comment by SebConejo** [comment]
@brunobuddy J'approuve la PR mais j'ai ajouté une issue

**Review by SebConejo — APPROVED** [review]

**Pull request merged**
