### PR TITLE
enhancement Style API Docs

### PR DESCRIPTION
**Pull request by LoayTarek5**
## Description
#133 
## Related Issues
This PR Fix the API documentation, Now the titles of response are easy to read and noticeable by adding some space, change color and add border left
## How can it be tested?
N/A

## Impacted packages

Check the NPM packages that require a new publication or release:

- [x] [manifest](https://www.npmjs.com/package/manifest)
- [x] [@mnfst/sdk](https://www.npmjs.com/package/@mnfst/sdk)

## Check list before submitting

- [x] I have performed a self-review of my code (no debugs, no commented code, good naming, etc.)
- [ ] I wrote the relative tests
- [x] I created a PR for the [documentation](https://github.com/mnfst/docs) if necessary and attached the link to this PR
- [x] This PR is wrote in a clear language and correctly labeled

### CODE REVIEW

**Comment by SebConejo** [comment]
@LoayTarek5 This time the code works. Viewing the result I have some suggestions. As you chose a vibrant color, I think we don't need anymore the small border and padding-left. Could you remove it ?

It works well without and the design is more consistent. 
Capture d’écran 2024-10-04 à 10 27 36

**Review by SebConejo — COMMENTED** [review]
@LoayTarek5 This time the code works. Viewing the result I have some suggestions. As you chose a vibrant color, I think we don't need anymore the small border and padding-left. Could you remove it ?

It works well without and the design is more consistent. 
Capture d’écran 2024-10-04 à 10 27 36

**Review by SebConejo — APPROVED** [review]

**Comment by brunobuddy** [comment]
@LoayTarek5 @SebConejo thank you for your work !

The failing tests were because of some regression. You can merge the last `develop` version in this branch and it should pass.

However those PRs should be done on the `develop` branch as explained on [the contributing file](https://github.com/mnfst/manifest/blob/master/CONTRIBUTING.md#branches). The title says "fix" but I see it more as an visual enhancement than a bug fix.

Cheers !

**Comment by LoayTarek5** [comment]
@brunobuddy I  changed the base branch from master to develop
is that right?

**Comment by brunobuddy** [comment]
@LoayTarek5 yes and now you can merge the develop branch in yours to update the tests.

**Comment by LoayTarek5** [comment]
@brunobuddy"Am I finished?"

**Review by SebConejo — APPROVED** [review]

**Comment by brunobuddy** [comment]
@LoayTarek5 good job !

**Pull request merged**
