### PR TITLE
Fix Style API docs

### PR DESCRIPTION
**Pull request by LoayTarek5**
## Issue Number
#133 

## Description
This PR Fix the API documentation, Now the titles of response are easy to read and noticeable by adding some space, change color and add border left
## Related Issues
N/A
## Impacted packages

Check the NPM packages that require a new publication or release:

- [x] [manifest](https://www.npmjs.com/package/manifest)
- [x] [@mnfst/sdk](https://www.npmjs.com/package/@mnfst/sdk)

## Check list before submitting

- [x] I have performed a self-review of my code (no debugs, no commented code, good naming, etc.)
- [ ] I wrote the relative tests
- [x] I created a PR for the [documentation](https://github.com/mnfst/docs) if necessary and attached the link to this PR
- [x] This PR is wrote in a clear language and correctly labeled

### CODE REVIEW

**Comment by SebConejo** [comment]
@LoayTarek5 Your work deployed today should take into account the latest version of master, pushed yesterday.

**Review by SebConejo — CHANGES_REQUESTED** [review]
@LoayTarek5 Your work deployed today should take into account the latest version of master, pushed yesterday.

**Review by SebConejo — CHANGES_REQUESTED** [review]
@LoayTarek5 I can't accept this PR for several reasons:
- Why did you modify settings.json and main.ts ? 
- You still didn't take into account the last version.

You just have to merge the last version on your branch and make sure there is no one conflict. Or you can make a new pr from the last commit if you prefer.

**Comment by LoayTarek5** [comment]
@SebConejo ok i will make a new branch 
But the main.ts needs to be modified due to a change in the style, as you mentioned.
image

**Comment by SebConejo** [comment]
> @SebConejo ok i will make a new branch But the main.ts needs to be modified due to a change in the style, as you mentioned. image

@LoayTarek5  Yes, you're right about the main.ts modifications

**Pull request closed without merging**
