### PR TITLE
Update pull_request_template.md with grammar update

### PR DESCRIPTION
**Pull request by JeffJeff4252**
## Impacted packages

Check the NPM packages that require a new publication or release:

- [ ] [manifest](https://www.npmjs.com/package/manifest)
- [] [add-manifest](https://www.npmjs.com/package/add-manifest)
- [ ] [@mnfst/sdk](https://www.npmjs.com/package/@mnfst/sdk)

## Check list before submitting

- [ ] I have performed a self-review of my code (no debugs, no commented code, good naming, etc.)
- [ ] I wrote the relative tests
- [ ] I created a PR for the [documentation](https://github.com/mnfst/docs) if necessary and attached the link to this PR
- [ ] This PR is wrote in a clear language and correctly labeled

### CODE REVIEW

**Review by brunobuddy — CHANGES_REQUESTED** [review]
Hello @JeffJeff4252 

Thank you for your contribution ! I think the correct form is "have written" if my English is correct.

**Comment by JeffJeff4252** [comment]
Hello @brunobuddy 

Both work.

**Comment by brunobuddy** [comment]
@JeffJeff4252 chatgpt does not agree

The correct form depends on the tense you're aiming to use. Here's a breakdown:

Correct form:

"I have written" (present perfect tense)
Example: I have written a book.
"I wrote" (simple past tense):
Use this if you're talking about a specific past action.
Example: I wrote an email yesterday.

Why?
"Wrote" is the past tense of write.
"Written" is the past participle, which is used with auxiliary verbs like have or has.
Let me know if you'd like more examples! 😊

**Comment by brunobuddy** [comment]
I am closing this PR as it is does not solve any problem

**Pull request closed without merging**
