### PR TITLE
_switch-yield SCSS Code Refactor

### LINKED ISSUE #148: Fix 'Duplicate Code' issue in packages\core\admin\src\styles\components\_switch-yield.scss
[CodeFactor](https://www.codefactor.io/repository/github/mnfst/manifest) found an issue: Duplicate Code

It's currently on:
[packages\core\admin\src\styles\components\_switch-yield.scss:223-231](https://www.codefactor.io/repository/github/mnfst/manifest/source/develop/packages/core/admin/src/styles/components/_switch-yield.scss#L223)
[packages\core\admin\src\styles\components\_switch-yield.scss:255-263](https://www.codefactor.io/repository/github/mnfst/manifest/source/develop/packages/core/admin/src/styles/components/_switch-yield.scss#L255)

### PR DESCRIPTION
**Pull request by nitesh2920**
## Description
Refactored SCSS to eliminate duplicate code by introducing mixins for shared styles.

## Related Issues
Closes #148.

## How can it be tested?
Review the updated SCSS files.

## Impacted packages
No packages Impacted

Check the NPM packages that require a new publication or release:

- [x] [manifest](https://www.npmjs.com/package/manifest)
- [x] [@mnfst/sdk](https://www.npmjs.com/package/@mnfst/sdk)

## Check list before submitting

- [x] I have performed a self-review of my code (no debugs, no commented code, good naming, etc.)
- [ ] I wrote the relative tests
- [ ] I created a PR for the [documentation](https://github.com/mnfst/docs) if necessary and attached the link to this PR
- [x] This PR is wrote in a clear language and correctly labeled

### CODE REVIEW

**Comment by nitesh2920** [comment]
@brunobuddy any updates on this ?

**Comment by SebConejo** [comment]
@nitesh2920 Can't clone your work. could you check your repo permissions ? It looks like it's private, by ssh key or something else.

**Comment by nitesh2920** [comment]
@SebConejo  I tried cloning on another system, and there were no issues can you please try again.

**Comment by SebConejo** [comment]
@nitesh2920 Sorry for leeting you know only jnow regarding your work. 

First, thank you for your contribution. we're going to close this pr because the yield switch is not a component used in Manifest after all.

Regarding your work, creating mixins to avoid the problem was a good start. But there's always duplication in that mixin. The  :before and :after pseudo-elements are called twice, and then the second time only serves to overwrite the background value set in the first call. So the error persists.

**Pull request closed without merging**
